### ISSUE TITLE
FE05.1: Create upload page

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-FE-Project#27]
- Need: #7 
- Related: 
- Approval Standards:
- Reason for the estimated point:
- Solution:

- [ ] Make a page implement #7
- [ ] After file is submit successful route to #28

**Comment by nnh53** [comment]
@hoangday185 hurry hurry

**Comment by nnh53** [comment]
@hoangday185 make a simple page that have title or header

**Comment by hoangday185** [comment]
I have problem like this 

![image](https://github.com/PiedTeam/DreameCloneTraining-FE-Project/assets/108289635/2b4bbd9d-5f28-4835-b433-8ff9f73957b4)

@nnh53 can you help me

**Comment by hoangday185** [comment]
@nnh53 because we use reactjs with sever side rendering, now i need more time to config for react-router-dom

**Comment by hoangday185** [comment]
@nnh53 review for me

**Comment by nnh53** [comment]
> @nnh53 i found that i react router don't work with vite, i researching about this so can you increase point

okay so is 1 point okay
