### ISSUE TITLE
FE06.3: Display data to confirm import table

### ISSUE THREAD

**Issue by hoangday185** [PiedTeam/DreameCloneTraining-FE-Project#29]
- Need: #28 #32 
- Related: #6 
- Approval Standards:
- Reason for the estimated point:
- Solution:
- [x] Display data

**Comment by nnh53** [comment]
move to sprint 4

**Comment by nnh53** [comment]
transfer issue to @hoangday185

**Comment by nnh53** [comment]
@hoangday185 actually already done in #28 right ??

**Comment by hoangday185** [comment]
css not done @nnh53
