### ISSUE TITLE
FE01: Research Ant Design Table

### ISSUE THREAD

**Issue by nnh53** [PiedTeam/DreameCloneTraining-FE-Project#9]
- Approval Standards
  - Succesfully show a table like excel

**Comment by nnh53** [comment]
This task need to be done before #7

**Comment by CiscoTran** [comment]
#Ant Design Table documentation:

https://ant.design/components/table

**Comment by nnh53** [comment]
@CiscoTran capture a screenshoot of the component you have done

**Comment by nnh53** [comment]
-  Capture a screenshoot of the component you have done @CiscoTran 
-

**Comment by nnh53** [comment]
- 17/4 team member leave team, pending task to other other person

**Comment by hoangday185** [comment]
@hoangday185 self-assigned at sprint 3

**Comment by hoangday185** [comment]
![Image](https://github.com/PiedTeam/DreameCloneTraining-FE-Project/assets/108289635/af41fdc1-2947-4aac-ad96-3c625ef2bd98)

[see more in here](https://ant.design/components/table)

**Comment by nnh53** [comment]
"review for me" not preview for me :)
